# FastAgent Configuration File

# Default Model Configuration:
# 
# Takes format:
#   <provider>.<model_string>.<reasoning_effort?> (e.g. anthropic.claude-3-5-sonnet-20241022 or openai.o3-mini.low)
# Accepts aliases for Anthropic Models: haiku, haiku3, sonnet, sonnet35, opus, opus3
# and OpenAI Models: gpt-4o-mini, gpt-4o, o1, o1-mini, o3-mini
#
# If not specified, defaults to "haiku". 
# Can be overriden with a command line switch --model=<model>, or within the Agent constructor.

default_model: o3-mini

# Logging and Console Configuration:
logger:
    level: debug
    type: console
    path: logs/fastagent.jsonl

    # Switch the progress display on or off
    progress_display: true

    # Show chat User/Assistant messages on the console
    show_chat: true
    # Show tool calls on the console
    show_tools: true
    # Truncate long tool responses on the console 
    truncate_tools: true

# MCP Servers
mcp:
    servers:
        fetch:
            command: "uvx"
            args: ["mcp-server-fetch"]
        # filesystem:
        #     command: "npx"
        #     args: ["-y", "@modelcontextprotocol/server-filesystem", "."]
        # pulsemcp:
        #     command: "npx"
        #     args: ["-y", "pulsemcp-server"]
        # google-patents:
        #     command: "npx"
        #     args: ["-y", "@kunihiros/google-patents-mcp"]
        # patsnap-mcp:
        #     command: "node"
        #     args: ["/home/kunihiros/dev/aider/projects/patsnap-mcp/build/index.js"] # 実際のパスに修正が必要な場合があります
        # arxiv-mcp-server:
        #     command: "/home/kunihiros/.local/bin/uv"
        #     args: ["tool", "run", "arxiv-mcp-server", "--storage-path", "."]
        # tavily:
        #    command: "bash"
        #    args: ["-c", "npx -y tavily-mcp@0.1.3"]
        # # brave-search: # 必要であればコメント解除して設定
        # #     command: "npx"
        # #     args: ["-y", "@modelcontextprotocol/server-brave-search"]
        # claude-code-server:
        #     command: "npx"
        #     args: ["-y", "@kunihiros/claude-code-mcp"]
        # mem0:
        #     command: "/home/kunihiros/.local/bin/mcp-proxy"
        #     args: ["http://127.0.0.1:6789/sse"] # mem0サーバーがこのURLで動作している前提
        # sequential-thinking:
        #     command: "npx"
        #     args: ["-y", "@modelcontextprotocol/server-sequential-thinking"]
        # rag-web-browser:
        #     command: "node"
        #     args: ["/home/kunihiros/dev/aider/projects/mcp-server-rag-web-browser/build/index.js"] # 実際のパスに修正が必要な場合があります